//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Todo1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Todo
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
    
        public virtual Status_table Status_table { get; set; }
    }
}
